name: Xcode Build

on:
  push:
    branches:
      - main # Or your default branch name
  pull_request:
    branches:
      - main # Or your default branch name

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build Xcode Project
      run: xcodebuild build -project Something.xcodeproj -scheme Something
